
export const NEXT_PUBLIC_API_BASE_URL_BACKEND = process.env.NEXT_PUBLIC_API_BASE_URL_BACKEND;
export const NEXT_PUBLIC_SERVICE_ID_EMAIL_JS = process.env.NEXT_PUBLIC_SERVICE_ID_EMAIL_JS;
export const NEXT_PUBLIC_TEMPLATE_ID_EMAIL_JS = process.env.NEXT_PUBLIC_TEMPLATE_ID_EMAIL_JS;
export const NEXT_PUBLIC_USER_ID_EMAIL_JS = process.env.NEXT_PUBLIC_USER_ID_EMAIL_JS;
