# docker-compose.yml
version: "3.9"

services:
  backend:
    build: .
    container_name: portfolio-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_USER: flor
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
